<script lang="ts">
  import { browser } from '$app/environment';
  import confetti from 'canvas-confetti';
  import { onMount, tick } from 'svelte';

  const STORAGE_KEY = 'bowers-evidence-progress-v1';

  type EvidenceItem = {
    id: string;
    title: string;
    subtitle: string;
    description: string;
    prompt: string;
    placeholder: string;
    solution: string;   // expected answer (lowercased compare)
    active: boolean;    // if false → “coming soon” card
    rewardText?: string;
    emoji: string;   // 👈 this will now BE the image
  };

  type EvidenceState = {
    input: string;
    isChecking: boolean;
    isValidated: boolean;
    isShaking: boolean;
  };

  // 👉 Configure your evidence cards here
  const evidenceItems: EvidenceItem[] = [
{
  id: 'hexcode',
  emoji: '🔐',
  title: 'Bewijsstuk 3: Hexadecimale Kluiscode',
  subtitle: 'Forensische omzettingen tussen decimaal en hex',
  description:
    'In het politiedossier lag een oude kluis met acht waardes in gemengde notaties. Alleen door correcte omzetting van alle waardes kan de kluis worden geopend.',
  prompt:
    'Wat is de kluiscode die ontstaat wanneer je van elke door jou omgezette waarde het laatste teken achter elkaar zet?',
  placeholder: '8 tekens',
  solution: '6744C0B5',
  active: true,
  rewardText:
    'De kluis opent met de code 6744C0B5. Binnenin ligt een map met verouderde locatiegegevens, die wijzen op het feit dat Bowers niet alleen was met het slachtoffer tijdens de moord. '
},


{
  id: 'fingerprint',
  emoji: '🧬',
  title: 'Bewijsstuk 1: Vingerafdruk',
  subtitle: 'Twee bestandsformaten van hetzelfde spoor',
  description: '',
  prompt:
    'Welk type afbeelding is NIET geschikt als directe digitale scan van een echte vingerafdruk?',
  placeholder: 'vector of bitmap',
  solution: 'vector',
  active: true,
  rewardText:
    'Uit de vergelijking van de PNG en de PDF blijkt dat deze vingerafdruk niet als ruwe bitmap-scan is opgeslagen, maar uit een vectorbron komt ("Generated by FakeFingerInc"). De herkomst van het beeld is daardoor onduidelijk; als zelfstandig digitaal bewijs wordt dit spoor afgekeurd.'
},


{
  id: 'audio',
  emoji: '🎙️',
  title: 'Bewijsstuk 2: Getuigenfragment',
  subtitle: 'Verborgen informatie in audiokanalen',
  description:
    'Dit geluidsfragment werd in het dossier als “onbruikbaar” bestempeld wegens zware ruis. Jullie onderzoeken of er toch verstaanbare informatie in verborgen zit.',
  prompt:
    'Welk woord uit de verklaring gebruik je als bewijs dat dit fragment toch relevante informatie bevat?',
  placeholder: 'codewoord',
  solution: 'vlieg',
  active: true,
  rewardText:
    'Door de audiokanalen te scheiden, blijkt de getuigenverklaring alsnog hoorbaar. De zin “hij heeft nog nooit een vlieg kwaad gedaan” zet de zaak tegen Jeremy Bowers verder onder druk. Dit bewijsstuk wordt voorlopig als relevant beschouwd.'
},



    // 👇 Voorbeeld “coming soon” kaarten
    {
      id: 'image-compression',
      emoji: '.',
      title: 'Bewijsstuk 4',
      subtitle: 'Binnenkort beschikbaar',
      description:
        'Een foto uit het dossier lijkt zwaar gecomprimeerd. Later onderzoek je of er details verloren zijn gegaan.',
      prompt: '',
      placeholder: '',
      solution: '',
      active: false
    },
    {
      id: 'file-formats',
      emoji: '.',
      title: 'Bewijsstuk 5',
      subtitle: 'Binnenkort beschikbaar',
      description:
        'Een mysterieus bestand zonder extensie duikt op in de zaak-Bowers. Later onderzoek je wat het echt is.',
      prompt: '',
      placeholder: '',
      solution: '',
      active: false
    }
  ];

  let evidenceStates: EvidenceState[] = evidenceItems.map((item) => ({
    input: '',
    isChecking: false,
    isValidated: false,
    isShaking: false
  }));

  let inputRefs: HTMLInputElement[] = [];

  // Load progress from localStorage
  onMount(() => {
    if (!browser) return;
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;

    try {
      const saved: Record<string, boolean> = JSON.parse(raw);
      evidenceItems.forEach((item, index) => {
        if (saved[item.id]) {
          evidenceStates[index].isValidated = true;
        }
      });
      evidenceStates = [...evidenceStates];
    } catch (e) {
      console.warn('Kon opgeslagen bewijs-progress niet lezen:', e);
    }
  });

  // Derived: counts
  $: totalActive = evidenceItems.filter((e) => e.active).length;
  $: validatedCount = evidenceItems.filter(
    (e, i) => e.active && evidenceStates[i].isValidated
  ).length;
$: allValidated = validatedCount === totalActive + 6;


  function persistProgress() {
    if (!browser) return;
    const progress: Record<string, boolean> = {};
    evidenceItems.forEach((item, index) => {
      if (evidenceStates[index].isValidated) {
        progress[item.id] = true;
      }
    });
    localStorage.setItem(STORAGE_KEY, JSON.stringify(progress));
  }

  function tinyConfetti() {
    if (!browser) return;
    confetti({
      particleCount: 80,
      spread: 70,
      origin: { y: 0.6 }
    });
  }

  function triggerShake(index: number) {
    evidenceStates[index].isShaking = true;
    evidenceStates = [...evidenceStates];
    setTimeout(() => {
      evidenceStates[index].isShaking = false;
      evidenceStates = [...evidenceStates];
    }, 500);
  }

  async function validateEvidence(index: number) {
    const item = evidenceItems[index];
    const state = evidenceStates[index];

    if (!item.active || state.isChecking || state.isValidated) return;

    if (!state.input.trim()) {
      await tick();
      inputRefs[index]?.focus();
      return;
    }

    state.isChecking = true;
    evidenceStates = [...evidenceStates];

    const delay = Math.floor(Math.random() * 800) + 500;

    setTimeout(async () => {
      state.isChecking = false;

      const expected = item.solution.trim().toLowerCase();
      const actual = state.input.trim().toLowerCase();

      if (expected && actual === expected) {
        state.isValidated = true;
        evidenceStates = [...evidenceStates];
        tinyConfetti();
        persistProgress();
      } else {
        state.input = '';
        evidenceStates = [...evidenceStates];
        triggerShake(index);
        await tick();
        inputRefs[index]?.focus();
      }
    }, delay);
  }

  function handleKeydown(index: number, event: KeyboardEvent) {
    if (event.key === 'Enter') {
      validateEvidence(index);
    }
  }
</script>
<title>Bewijsdossier</title>

<main class="min-h-screen bg-gray-950 text-gray-100 flex flex-col items-center p-6">
  <!-- Header -->
  <header class="w-full max-w-5xl mb-8 text-center">
    <h1 class="text-4xl md:text-5xl font-extrabold mb-6">
      Zaak Bowers: Digitaal bewijsdossier
    </h1>

      <!-- Eindrapport-knop: zichtbaar, maar eerst vergrendeld -->
  <section class="w-full max-w-5xl mt-6 flex justify-center">
    <a
      href={allValidated ? '/bowers/final-report' : undefined}
      aria-disabled={!allValidated}
      class={`inline-flex items-center gap-2 px-6 py-3 rounded-full text-sm md:text-base font-semibold 
              border transition-all duration-200
              ${allValidated
                ? 'bg-gradient-to-r from-emerald-500 to-indigo-500 text-white border-transparent shadow-lg hover:shadow-emerald-400/70 hover:scale-105 cursor-pointer'
                : 'bg-gray-900 text-gray-500 border-gray-700 cursor-not-allowed opacity-70 pointer-events-none'}`}
    >
      <span class="text-lg">
        {allValidated ? '🔓' : '🔒'}
      </span>
      <div class="flex flex-col items-start leading-tight">
        <span>
          {allValidated ? 'Open eindrapport' : 'Eindrapport vergrendeld'}
        </span>
        <span class="text-[0.7rem] uppercase tracking-wide text-gray-400">
          {validatedCount} / ? bewijsstukken
        </span>
      </div>
    </a>
  </section>

  </header>

  <!-- Evidence grid -->
  <section class="w-full max-w-5xl grid gap-6 md:grid-cols-2">
    {#each evidenceItems as item, i}
      <article
        class="relative flex flex-col bg-gray-900 border border-gray-800 rounded-2xl p-5 shadow-xl
               hover:border-indigo-500/60 transition-all duration-300"
      >
        <!-- Status badge -->
        <div class="absolute top-3 right-3">
          {#if !item.active}
            <span class="px-3 py-1 text-xs font-semibold rounded-full bg-gray-800 text-gray-400 border border-gray-700">
              Binnenkort
            </span>
              {:else if evidenceStates[i].isValidated}
                {#if item.id === 'fingerprint'}
                  <span class="px-3 py-1 text-[0.6rem] font-semibold rounded-full bg-red-900 text-red-200 border border-red-500/70">
                    ❌ Afgekeurd
                  </span>
                {:else}
                  <span class="px-3 py-1 text-[0.6rem] font-semibold rounded-full bg-emerald-900 text-emerald-200 border border-emerald-500/70">
                    ✅ Gevalideerd
                  </span>
                {/if}

          {:else}
            <span class="px-3 py-1 text-xs font-semibold rounded-full bg-indigo-900 text-indigo-200 border border-indigo-500/70">
              Actief
            </span>
          {/if}
        </div>

        <!-- Card header -->
        <div class="mb-3 mt-4">
          <h2 class="text-2xl font-bold">{item.title}</h2>
          <p class="text-sm text-indigo-300">{item.subtitle}</p>
        </div>

        <!-- Emoji evidence preview -->
        <div class="mb-3 flex items-center justify-center h-24">
          <span class="text-6xl drop-shadow">
            {#if item.active}
              {item.emoji}
            {:else}
              ❓
            {/if}
          </span>
        </div>

        {#if item.active}
        <p class="text-sm text-indigo-200 mb-2"> {item.prompt} </p>
          <!-- Active evidence: input + button -->
          <div class="">

            <input
              type="text"
              bind:value={evidenceStates[i].input}
              bind:this={inputRefs[i]}
              placeholder={item.placeholder}
              disabled={evidenceStates[i].isChecking || evidenceStates[i].isValidated}
              on:keydown={(e) => handleKeydown(i, e)}
              class="w-full p-3 mb-3 text-lg font-mono rounded-lg bg-gray-950 text-indigo-100
                     border-2 border-gray-700 focus:outline-none focus:border-indigo-400
                     focus:ring-2 focus:ring-indigo-500/60 transition-all duration-200
                     {evidenceStates[i].isShaking ? 'animate-shake' : ''}"
            />

            <button
              on:click={() => validateEvidence(i)}
              disabled={evidenceStates[i].isChecking || evidenceStates[i].isValidated}
              class="w-full px-4 py-2.5 rounded-full text-base font-semibold
                     bg-gradient-to-r from-indigo-600 to-purple-500
                     hover:from-purple-500 hover:to-indigo-500
                     shadow-md hover:shadow-indigo-500/50
                     transition-transform duration-150 transform hover:scale-[1.02]
                     active:scale-95 disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {#if evidenceStates[i].isValidated}
                ✅ Bewijs geanalyseerd
              {:else if evidenceStates[i].isChecking}
                ⏳ Beoordelen...
              {:else}
                🔍 Beoordeel bewijs
              {/if}
            </button>

            {#if evidenceStates[i].isValidated && item.rewardText}
              <p class="mt-3 text-sm text-emerald-200">
                {item.rewardText}
              </p>
            {/if}
          </div>
        {:else}
          <!-- Coming soon state -->
          <div class="mt-6 flex flex-col items-center justify-center py-6 border-t border-gray-800">
            <p class="text-sm text-gray-400 text-center">
              Dit bewijsstuk wordt later in het onderzoek geopend.
            </p>
          </div>
        {/if}
      </article>
    {/each}
  </section>



</main>

<style>
  @keyframes shake {
    0%, 100% { transform: translateX(0); }
    15%, 85% { transform: translateX(-6px); }
    30%, 70% { transform: translateX(6px); }
    45%, 55% { transform: translateX(-8px); }
  }
  .animate-shake {
    animation: shake 0.4s ease-in-out;
  }
</style>
